[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
gloo-net = { version = "0.6", features = ["websocket"] }
wasm-bindgen-futures = "0.4"
futures-util = "0.3"
web-sys = "0.3"

[features]
csr = []